version: '3'
services:

# turn-server:
#   build: ./turn/
#   container_name: turn-server
#   image: turn
#   ports:
#     - "3478:3478/tcp"
#     - "3478:3478/udp"
#   networks:
#     - webrtc

  signaling-server:
    image: signaling
    build: ./signaling/
    container_name: signaling-server
    ports:
      - "9999:9999"
    networks:
      - webrtc

  web-server:
    image: web-server
    build:
      context: ./web
      dockerfile: server.Dockerfile
    container_name: web-server
    ports:
      - "5000:5000"
    networks:
      - webrtc

  web-client:
    image: web-client
    build:
      context: ./web
      dockerfile: client.Dockerfile
    container_name: web-client
    ports:
      - "5001:5001"
    networks:
      - webrtc

networks:
    webrtc:
