version: '3'

services:

# turn-server:
#   build: ./turn/
#   container_name: turn-server
#   image: turn
#   ports:
#     - "3478:3478/tcp"
#     - "3478:3478/udp"
#   networks:
#     - webrtc

  signaling-server:
    build: ./signaling/
    container_name: signaling-server
    image: signaling
    ports:
      - "9999:9999"
    networks:
      - webrtc


  web-server:
    build: ./server/
    container_name: web-server
    image: web-server
    ports:
      - "8000:8000"
    networks:
      - webrtc

  web-client:
    build: ./client/
    container_name: web-client
    image: web-client
    ports:
      - "7000:7000"
    networks:
      - webrtc

networks:
    webrtc:
